name: MovieDB CI

on:
  push:
    branches: 
    - build_app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    #setup the flutter enviroment
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    
    #get flutter dependencies
    - run : flutter pub get

    # Run widget tests for our flutter project.
    - run: flutter test
    
    # Build apk.
    - run: flutter build apk
    
    #Upload generated apk to the artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
